### ISSUE TITLE
threshold_values error

### ISSUE THREAD

**Issue by pacey** [thenayr/dashing-newrelic#12]
Hi,

When I start up my dashboard I get the following error:

```
scheduler caught exception:
undefined method `threshold_values' for nil:NilClass
/Users/jamesp/Sandboxes/frodin-dashboard/lib/newrelic.rb:26:in `get_value'================================================================================
scheduler caught exception:
undefined method `threshold_values' for nil:NilClass
/Users/jamesp/Sandboxes/frodin-dashboard/lib/newrelic.rb:26:in `get_value'
/Users/jamesp/Sandboxes/frodin-dashboard/jobs/newrelic_error.rb:9:in `block in <top (required)>'

/Users/jamesp/Sandboxes/frodin-dashboard/jobs/newrelic_apdex.rb:9:in `block in <top (required)>'/Users/jamesp/.rvm/gems/ruby-1.9.3-p551/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
```

**Comment by warrenguy** [comment]
Most likely your `app_name` is not correctly configured.
